name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  GO_VERSION: '1.23.4'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: make test
