name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/release.yaml'
      - 'scripts/**'
      - 'Makefile'

env:
  GO_VERSION: '1.23.4'

permissions:
  contents: write
  deployments: write

jobs:
  generate-artifacts:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ARCH: [amd64, arm64]
    outputs:
      binary_name_amd64: ${{ steps.set_outputs.outputs.binary_name_amd64 }}
      binary_name_arm64: ${{ steps.set_outputs.outputs.binary_name_arm64 }}
    env:
      ARCH: ${{ matrix.ARCH }}
      RELEASE_TAG: ''
      BINARY_NAME: ''
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Export release tag
        run: |
          export release_tag=${GITHUB_REF#refs/*/} # Strip down to raw tag name
          echo "RELEASE_TAG=${release_tag}" >> $GITHUB_ENV
      - name: Create dummy environment for release
        if: github.event_name == 'pull_request'
        run: echo "RELEASE_TAG=v0.0.0" >> $GITHUB_ENV
      - name: Setup variables
        run: |
          export release_tag=${{ env.RELEASE_TAG }}
          export release_version=${release_tag/v/} # Remove v from tag name
          echo "BINARY_NAME=zvol-snapshotter-${release_version}-linux-${ARCH}.tar.gz" >> $GITHUB_ENV
      - name: Create release binaries
        run: ARCH=${{ env.ARCH }} RELEASE_TAG=${{ env.RELEASE_TAG }} make release
      - uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ env.ARCH }}
          path: release/
          if-no-files-found: error
      - name: Set outputs
        id: set_outputs
        run: |
          echo "binary_name_${{ env.ARCH }}=${{ env.BINARY_NAME }}" >> $GITHUB_OUTPUT

  create-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [generate-artifacts]
    runs-on: ubuntu-24.04
    env:
      RELEASE_TAG: ''
    steps:
      - uses: actions/checkout@v4
      - name: Export release tag
        run: |
          export release_tag=${GITHUB_REF#refs/*/} # Strip down to raw tag name
          echo "RELEASE_TAG=${release_tag}" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: release-artifacts-amd64
      - uses: actions/download-artifact@v4
        with:
          name: release-artifacts-arm64
      - uses: softprops/action-gh-release@v2
        with:
          name: "zvol-snapshotter ${{ env.RELEASE_TAG }}"
          draft: true
          prerelease: false
          generate_release_notes: true
          files: |
            ${{ needs.generate-artifacts.outputs.binary_name_amd64 }}
            ${{ needs.generate-artifacts.outputs.binary_name_amd64 }}.sha256sum
            ${{ needs.generate-artifacts.outputs.binary_name_arm64 }}
            ${{ needs.generate-artifacts.outputs.binary_name_arm64 }}.sha256sum